apiVersion: dataplane.openstack.org/v1beta1
kind: OpenStackDataPlaneService
metadata:
  name: install-os
spec:
  label: dataplane-deployment-install-os
  role:
    name: "Deploy EDPM Operating System Install"
    hosts: "all"
    strategy: "linear"
    become: true
    tasks:
      - name: "Install edpm_bootstrap"
        import_role:
          name: "osp.edpm.edpm_bootstrap"
          tasks_from: "bootstrap.yml"
        tags:
          - "edpm_bootstrap"
      - name: "Install edpm_kernel"
        import_role:
          name: "osp.edpm.edpm_kernel"
          tasks_from: "main.yml"
        tags:
          - "edpm_kernel"
      - name: "Install edpm_podman"
        import_role:
          name: "osp.edpm.edpm_podman"
          tasks_from: "install.yml"
        tags:
          - "edpm_podman"
      - name: "Install edpm_sshd"
        import_role:
          name: "osp.edpm.edpm_sshd"
          tasks_from: "install.yml"
        tags:
          - "edpm_sshd"
      - name: "Install edpm_chrony"
        import_role:
          name: "osp.edpm.edpm_chrony"
          tasks_from: "install.yml"
        tags:
          - "edpm_chrony"
      - name: "Install edpm_ovn"
        import_role:
          name: "osp.edpm.edpm_ovn"
          tasks_from: "install.yml"
        tags:
          - "edpm_ovn"
      - name: "Install edpm_logrotate_crond"
        import_role:
          name: "osp.edpm.edpm_logrotate_crond"
          tasks_from: "install.yml"
        tags:
          - "edpm_logrotate_crond"
      - name: "Install edpm_iscsid"
        import_role:
          name: "osp.edpm.edpm_iscsid"
          tasks_from: "install.yml"
        tags:
          - "edpm_iscsid"
