apiVersion: dataplane.openstack.org/v1beta1
kind: OpenStackDataPlaneService
metadata:
  name: neutron-dhcp
spec:
  playbook: osp.edpm.neutron_dhcp
  dataSources:
    - secretRef:
        name: neutron-dhcp-agent-neutron-config
  caCerts: combined-ca-bundle
  containerImageFields:
  - EdpmNeutronDhcpAgentImage
