apiVersion: dataplane.openstack.org/v1beta1
kind: OpenStackDataPlaneService
metadata:
  name: swift
spec:
  playbook: osp.edpm.swift
  dataSources:
    - secretRef:
        name: swift-conf
    - configMapRef:
        name: swift-storage-config-data
    - configMapRef:
        name: swift-ring-files
