apiVersion: dataplane.openstack.org/v1beta1
kind: OpenStackDataPlaneService
metadata:
  name: logging
spec:
  dataSources:
    - secretRef:
        name: logging-compute-config-data
  playbook: osp.edpm.telemetry_logging
