= dataplane-operator

The dataplane-operator automates the deployment of an OpenStack dataplane. A
dataplane is a collection of nodes that will be used for hosting OpenStack
workloads. The dataplane-operator prepares the nodes with enough operating
system configuration so that they are ready for hosting other required
OpenStack services and workloads.

See https://openstack-k8s-operators.github.io/dataplane-operator/contributing/[contributing] for notes for developers and
contributors, running the operator, building the documentation, etc.

See https://openstack-k8s-operators.github.io/dataplane-operator/design/[design] for details about the dataplane design.

https://openstack-k8s-operators.github.io/dataplane-operator/deploying/[Deploying a DataPlane] documents how to deploy a dataplane.

The documentation source is kept within the dataplane-operator repo in the
https://github.com/openstack-k8s-operators/dataplane-operator/tree/main/docs[docs] directory. The full
generated documentation from that source is available at
https://openstack-k8s-operators.github.io/dataplane-operator/.

== License

Copyright 2023.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

 http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
