[id="proc_hotfixing-the-data-plane-rpm-content-{context}"]
= Hotfixing the data plane RPM content

[role="_abstract"]

RPM hotfix content is installed directly on to the data plane nodes.

.Procedure

. Obtain the RPM hotfix content from the source and store it locally.
+
----
$ mkdir -p <hotfix_id>/rpms
$ cp /path/to/hotfix/*.rpm <hotfix_id>/rpms
----
+
* Replace `<hotfix_id>` with a hotfix identifier such as a Jira issue, for example `osprh-0000`

. Copy the RPM hotfix content to the affected data plane nodes.
+
----
$ ssh <ssh_user>@<data_plane_node> mkdir -p /tmp/<hotfix_id>/rpms
$ scp <hotfix_id>/rpms/*.rpm <ssh_user>@<data_plane_node>:/tmp/<hotfix_id>/rpms
----
+
* Replace `<hotfix_id>` with a hotfix identifier such as a Jira issue, for example `osprh-0000`
* Replace `<ssh_user>` with the user name used for SSH
* Replace `<data_plane_node>` with the hostname or IP for the data plane node.
* Repeat the command for each affected data plane node.

. Update the RPM hotfix content on the affected data plane nodes.
+
----
$ ssh <ssh_user>@<data_plane_node>
$ sudo rpm -F /tmp/hotfix-rpms/*.rpm
----
+
* The `-F` (`--freshen`) `rpm` command option will update the RPM content if earlier versions are already installed.

. Complete any remaining custom steps to apply the RPM hotfix content
+
In some cases, custom steps may be required to complete applying the hotfix content. This may include restarting `systemd` services or other steps. Refer to the instructions that accompanied the hotifx and complete any necessary steps.
