apiVersion: dataplane.openstack.org/v1beta1
kind: OpenStackDataPlaneNode
metadata:
  name: openstackdataplanenode-sample
spec:
  role: openstackdataplanerole-sample
  hostName: openstackdataplanenode-sample.localdomain
  ansibleHost: 192.168.122.18
  node:
    services:
      - configure-network
      - validate-network
      - install-os
      - configure-os
      - run-os
    networks:
      - network: ctlplane
        fixedIP: 192.168.122.18
    ansibleSSHPrivateKeySecret: dataplane-ansible-ssh-private-key-secret
