apiVersion: dataplane.openstack.org/v1beta1
kind: OpenStackDataPlaneNode
metadata:
  name: edpm-compute-0-full
spec:
  hostName: edpm-compute-0
  ansibleHost: 192.168.122.100
  ansibleSSHPrivateKeySecret: dataplane-ansible-ssh-private-key-secret
  node:
    services:
      - configure-network
      - validate-network
      - install-os
      - configure-os
      - run-os
    nova: {}
    ansibleUser: root
    ansiblePort: 22
    ansibleSSHPrivateKeySecret: dataplane-ansible-ssh-private-key-secret
    ansibleVars: |
      tenant_ip: 192.168.24.100
      edpm_network_config_template: templates/net_config_bridge.j2
      edpm_network_config_hide_sensitive_logs: false
      neutron_physical_bridge_name: br-ex
      neutron_public_interface_name: eth0
      ctlplane_dns_nameservers:
      - 192.168.122.1
      dns_search_domains: []
      edpm_ovn_dbs: 192.168.24.1
      edpm_chrony_ntp_servers:
        - clock.redhat.com
        - clock2.redhat.com
      registry_name: "quay.io"
      registry_namespace: "podified-antelope-centos9"
      image_tag: "current-podified"
      edpm_ovn_controller_agent_image: "{{ registry_name }}/{{ registry_namespace }}/openstack-ovn-controller:{{ image_tag }}"
      edpm_iscsid_image: "{{ registry_name }}/{{ registry_namespace }}/openstack-iscsid:{{ image_tag }}"
      edpm_logrotate_crond_image: "{{ registry_name }}/{{ registry_namespace }}/openstack-cron:{{ image_tag }}"
      edpm_nova_compute_container_image: "{{ registry_name }}/{{ registry_namespace }}/openstack-nova-compute:{{ image_tag }}"
      edpm_nova_libvirt_container_image: "{{ registry_name }}/{{ registry_namespace }}/openstack-nova-libvirt:{{ image_tag }}"
      edpm_ovn_metadata_agent_image: "{{ registry_name }}/{{ registry_namespace }}/openstack-neutron-metadata-agent-ovn:{{ image_tag }}"
  deployStrategy:
    deploy: false
