= Contributing
:toc: left
:toclevels: 5

== Getting Started

You'll need a Kubernetes cluster to run against. You can use
https://sigs.k8s.io/kind[KIND] to get a local cluster for testing, or run
against a remote cluster.  *Note:* Your controller will automatically use the
current context in your kubeconfig file (i.e. whatever cluster `kubectl
cluster-info` shows).

=== Running on the cluster

. Install Instances of Custom Resources:
+
[,sh]
----
 kubectl apply -f config/samples/
----

. Build and push your image to the location specified by `IMG`:
+
[,sh]
----
 make docker-build docker-push IMG=<some-registry>/dataplane-operator:tag
----

. Deploy the controller to the cluster with the image specified by `IMG`:
+
[,sh]
----
 make deploy IMG=<some-registry>/dataplane-operator:tag
----

=== Uninstall CRDs

To delete the CRDs from the cluster:

[,sh]
----
make uninstall
----

=== Undeploy controller

UnDeploy the controller to the cluster:

[,sh]
----
make undeploy
----

=== How it works

This project aims to follow the Kubernetes https://kubernetes.io/docs/concepts/extend-kubernetes/operator/[Operator pattern]

It uses https://kubernetes.io/docs/concepts/architecture/controller/[Controllers]
which provide a reconcile function responsible for synchronizing resources
until the desired state is reached on the cluster

=== Test It Out

. Install the CRDs into the cluster:
+
[,sh]
----
 make install
----

. Run your controller (this will run in the foreground, so switch to a new terminal if you want to leave it running):
+
[,sh]
----
 make run
----

*NOTE:* You can also run this in one step by running: `make install run`

=== Modifying the API definitions

If you are editing the API definitions, generate the manifests such as CRs or CRDs using:

[,sh]
----
make manifests
----

*NOTE:* Run `make --help` for more information on all potential `make` targets

More information can be found via the https://book.kubebuilder.io/introduction.html[Kubebuilder Documentation]

== Testing

The tests can be run with the following command:

[,bash]
----
make test
----

The `test` target runs the
https://book.kubebuilder.io/reference/envtest.html[EnvTest] tests with
https://onsi.github.io/ginkgo/[Ginkgo]. These tools will be installed by the
`test` if needed.

`EnvTest` tests are under the
https://github.com/openstack-k8s-operators/dataplane-operator/tree/main/tests/functional[`tests/functional`]
directory in dataplane-operator.

=== Running kuttl tests

kuttl tests are under the
https://github.com/openstack-k8s-operators/dataplane-operator/tree/main/tests/kuttl/tests['tests/kuttl/tests']
in dataplane-operator and can be executed either directly from dataplane operator repository, or from https://github.com/openstack-k8s-operators/install_yamls[install_yamls]

==== Requirements

The kuttl tests require a running cluster with
https://github.com/openstack-k8s-operators/openstack-ansibleee-operator[openstack-ansibleee-operator], https://github.com/openstack-k8s-operators/openstack-baremetal-operator[openstack-baremetal-operator], https://github.com/openstack-k8s-operators/infra-operator[infra-operator]
and https://github.com/openstack-k8s-operators/rabbitmq-cluster-operator[rabbitmq-cluster-operator] running in the cluster.
The easiest way to ensure presence of these operators is to use install_yamls. However, it is possible to deploy them manually as well.

==== From install_yamls

First clone both the dataplane-operator and the install-yamls repos and make sure that they are in a state (commit) you want to test.
For the purposes of this guide, we will assume following directory layout:

....
~
├── dataplane-operator
└── install_yamls
....

[NOTE]
====
The kuttl tests are also run from the
https://github.com/openstack-k8s-operators/install_yamls[install_yamls]
repository by the CI jobs.
====

We will also assume that there is no cluster already running. If you already have a cluster, skip the following step.

Initialize your CRC with https://github.com/openstack-k8s-operators/install_yamls?tab=readme-ov-file#deploy-dev-env-using-crc-edpm-nodes-with-isolated-networks[install_yamls] utilities.
Make sure to have your pull secret ready and to fulfill all HW requirements. 
CRC can be initialized without install_yamls utilities. However, using existing scripts will simplify debugging and issue reporting.

Ensure presence of dataplane operator requirements and cleanup all remains of possible previous kuttl test run.

[,sh]
----
cd ..
make dataplane_kuttl_prep
make dataplane_cleanup
----

Moving to the dataplane-operator repo, we can start the dataplane operator itself. 

[NOTE]
====
Ports 8080 and 8081 are used for collection of metrics and health information. Make sure that they are not in use.
You can override them using `METRICS_PORT` and `HEALTH_PORT` vars. 
====

This will start dataplane operator in your shell. Either redirect the output or have another ready for next step.

[,sh]
----
cd ../dataplane-operator
make run
----

If your patch introduces any changes to resources, such as OpenStackDataPlaneDeployment, you have to apply them manually.
Otherwise the test suite will run without them.
Changes to existing resources can be introduced with `oc patch`, new resoruces require `oc apply`.

[,sh]
----
oc apply -f ./path/to/my/file.yaml
----

Finally, you can launch kuttl tests themselves.  
You can also apply configurations from your tests manually.

[,sh]
----
make kuttl-test
----

==== From dataplane-operator

The kuttl tests can also be run directly from the dataplane-operator checkout but
you need the operators listed under <<requirements,Requirements>>
When running from a dataplane-operator checkout, `kubectl-kuttl` must be
installed. The `kubectl-kuttl` command can be installed from
https://github.com/kudobuilder/kuttl/releases[kuttl releases], or using the
Makefile target `kuttl`:

[,sh]
----
make kuttl
----

Then, run the operator from a checkout:

[,sh]
----
make run
----

Execute the kuttl tests:

[,sh]
----
make kuttl-test
----

==== Using KUTTL_ARGS

Kuttl tests can be supplied with any arguments compatible with the installed version of https://kuttl.dev/docs/cli.html#commands[kuttl CLI], using the `KUTTL_ARGS` var.

For example to run a single test:

[,sh]
----
make kuttl-test KUTTL_ARGS="--test dataplane-deploy-no-nodes"
----

Skip the test resource delete, which will leave the test resources created in the
cluster, and can be useful for debugging failed tests:

[,sh]
----
make kuttl-test KUTTL_ARGS="--test dataplane-deploy-no-nodes --skip-delete"
----
