apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

namespace: openstack
nameSuffix: -ovs-dpdk-sriov

components:
- ../baremetal

resources:
  - values.yaml

replacements:
# OpenStackDataPlaneNodeSet customizations
- source:
    kind: DataPlaneConfig
    name: edpm-ovs-dpdk-sriov-values
    fieldPath: data.nodeset.nodetemplate.ansible.vars
  targets:
  - select:
      kind: OpenStackDataPlaneNodeSet
    fieldPaths:
    - spec.nodeTemplate.ansible.ansibleVars
    options:
      create: true
- source:
    kind: DataPlaneConfig
    name: edpm-ovs-dpdk-sriov-values
    fieldPath: data.nodeset.services
  targets:
  - select:
      kind: OpenStackDataPlaneNodeSet
    fieldPaths:
    - spec.services
    options:
      create: true
- source:
    kind: DataPlaneConfig
    name: edpm-ovs-dpdk-sriov-values
    fieldPath: data.nodeset.nodes
  targets:
  - select:
      kind: OpenStackDataPlaneNodeSet
    fieldPaths:
    - spec.nodes
    options:
      create: true
- source:
    kind: DataPlaneConfig
    name: edpm-ovs-dpdk-sriov-values
    fieldPath: data.nodeset.baremetalsettemplate
  targets:
  - select:
      kind: OpenStackDataPlaneNodeSet
    fieldPaths:
    - spec.baremetalSetTemplate
    options:
      create: true
- source:
    kind: DataPlaneConfig
    name: edpm-ovs-dpdk-sriov-values
    fieldPath: data.preProvisioned
  targets:
  - select:
      kind: OpenStackDataPlaneNodeSet
    fieldPaths:
    - spec.preProvisioned
    options:
      create: true
- source:
    kind: DataPlaneConfig
    name: edpm-ovs-dpdk-sriov-values
    fieldPath: data.nodeset.nodetemplate.networks
  targets:
  - select:
      kind: OpenStackDataPlaneNodeSet
    fieldPaths:
    - spec.nodeTemplate.networks
    options:
      create: true
